# Generated by Django 5.2 on 2025-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
