# Generated by Django 5.2 on 2025-06-15 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
