# Generated by Django 5.2 on 2025-06-18 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_alter_announcement_options_announcement_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineGiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_transaction_id', models.CharField(max_length=100)),
                ('purpose', models.CharField(default='Tithe', max_length=100)),
                ('thank_you_message', models.CharField(default='Thank you for your generosity!', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.member')),
            ],
        ),
    ]
