# Generated by Django 5.2 on 2025-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_onlinegiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinegiving',
            name='purpose',
            field=models.CharField(choices=[('tithes', 'Tithes'), ('thanks', 'Thanks'), ('offering', 'Offering'), ('donation', 'Donation')], default='tithes', max_length=20),
        ),
    ]
