# Generated by Django 5.2 on 2025-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_alter_onlinegiving_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegiving',
            name='giver_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinegiving',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
