# Generated by Django 5.2 on 2025-06-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_onlinegiving_giver_name_onlinegiving_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinegiving',
            old_name='purpose',
            new_name='category',
        ),
    ]
