# Generated by Django 5.2 on 2025-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_rename_purpose_onlinegiving_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
