# Generated by Django 5.2 on 2025-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_church_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegiving',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
