# Generated by Django 5.2 on 2025-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
