# Generated by Django 5.2 on 2025-06-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_activitylog_biblereadingplan_memberreadinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreadinglog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.member'),
        ),
    ]
