# Generated by Django 5.2 on 2025-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_alter_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayincomereceipt',
            name='category',
            field=models.CharField(choices=[('offering', 'Offering'), ('tithe', 'Tithe'), ('donation', 'Donation'), ('thanksgiving', 'Thanksgiving'), ('other', 'Other')], max_length=100),
        ),
    ]
