# Generated by Django 5.2 on 2025-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0023_alter_sundayincomereceipt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField()),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
