# Generated by Django 5.2 on 2025-07-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0026_chairmanmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('church_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('pro', 'Pro')], default='basic', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license', to='church.church')),
            ],
        ),
    ]
