# Generated by Django 5.2 on 2025-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Tick to disable all log‑ins for this church until dues are paid.'),
        ),
    ]
