# Generated by Django 5.2 on 2025-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0029_church_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_paid_txn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
