# Generated by Django 5.2 on 2025-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0030_subscription_last_paid_txn_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
