# Generated by Django 5.2 on 2025-07-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0031_alter_subscription_last_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_paid_txn',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
