# Generated by Django 5.2 on 2025-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0032_remove_subscription_last_paid_txn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
