# Generated by Django 5.2 on 2025-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0034_subscription_confirmed_at_subscription_confirmed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UPI Payment', max_length=100)),
                ('upi_id', models.CharField(help_text='e.g., yourname@upi', max_length=100)),
                ('qr_image', models.ImageField(upload_to='payment_qr/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
