# Generated by Django 5.2 on 2025-07-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0036_memberchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberchatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
