# Generated by Django 5.2 on 2025-07-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0037_memberchatmessage_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberchatmessage',
            options={'permissions': [('moderate_message', 'Can moderate member chat messages')]},
        ),
    ]
