# Generated by Django 5.2 on 2025-07-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0039_church_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pastor', 'Pastor'), ('associate_pastor', 'Associate Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('head_deacon', 'Head Deacon'), ('deaconess', 'Deaconess'), ('clerk', 'Clerk / Secretary'), ('choir_master', 'Choir Master / Song Leader'), ('pianist', 'Pianist'), ('drummer', 'Drummer'), ('guitarist', 'Guitarist'), ('auditor', 'Auditor'), ('sound_technician', 'Sound Technician'), ('projector_operator', 'Projector Operator'), ('security', 'Chowkidar / Security'), ('cleaner', 'Cleaner / Janitor'), ('groundskeeper', 'Groundskeeper'), ('sunday_school_superintendent', 'Sunday School Superintendent'), ('sunday_school_teacher', 'Sunday School Teacher'), ('other', 'Other')], max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='church.church')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_month', models.DateField(help_text='Use the 1st of the month to represent the payment period.')),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='church.churchstaffmember')),
            ],
        ),
    ]
