# Generated by Django 5.2 on 2025-07-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0040_churchstaffmember_staffpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayment',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
            preserve_default=False,
        ),
    ]
