# Generated by Django 5.2 on 2025-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0041_staffpayment_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='church_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
